# Some overall notes on how this works
#
# * We smoke using the system provided latest, and custom built "oddball perls"
# The reason for not having a blanket matrix is to conserve travis resources
# as a full DBIC depchain isn't cheap
#
# * Minimum perl officially supported by DBIC is 5.8.3. This *includes* the
# basic depchain. On failure either attempt to fix it or bring it to the
# attention of the maintainer. *DO NOT* disable 5.8 testing - it is here for
# a very good reason
#
# the entire run times out after 50 minutes, or after 5 minutes without
# console output

#
# Smoke all branches except for blocked* and wip/*
branches:
  except:
    - /^wip\//
    - /^blocked/

notifications:
  email:
    recipients:
      - CPAN-CI@leporine.io
    on_success: change
    on_failure: always

# IFF this list is changed - make sure to backfill the override-addons further down too
addons:
  apt:
    packages:
      - libapp-nopaste-perl
      - net-tools
      - expect

# This is probably a net-loss for setup etc - a bare 'C' will likely fare much better
language: perl

# Currently not trying osx: https://github.com/travis-ci/travis-ci/issues/2314
os: linux

# The defaults run under the older infra.
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: precise
env: CLEANTEST=true

perl:
  - "5.8"
  - "5.10"
  - "5.24-shrplib"

matrix:
  include:

    # Same as the "master matrix" above, frozen under older dist/infrastructure
    # In genereal it is strongly recommended to keep things on the older
    # version indefinitely - there is little value in-depth smoking on
    # more recent software stacks
    - perl: "5.8"
      dist: precise
      env:
        - CLEANTEST=false

    - perl: "5.10"
      dist: precise
      env:
        - CLEANTEST=false

    - perl: "5.24-shrplib"
      dist: precise
      env:
        - CLEANTEST=false

    # ASan-instrumented threaded latest 5.24 with, no tests on depchain ( run only DBICs tests )
    - perl: "livebrew_devcpan_5.24.4_thr_qm_asan"
      # FIXME - move to bionic
      dist: trusty
      env:
        - CLEANTEST=false
        - DEVREL_DEPS=true
        - POISON_ENV=true
        - MVDT=false
        - BREWVER=5.24.4
        - CC=gcc-8
        - CXX=g++-8
        # FIXME - something in perl confuses ASan, do no trace leaks for now
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250024.html
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250022.html
        - ASAN_OPTIONS=detect_leaks=0
        - ASAN_FLAGS_COMMON="-fsanitize=address -fuse-ld=gold -fno-omit-frame-pointer -g -O2"
        - BREWOPTS="-Duseithreads -Dusequadmath -Dcc=$CC -Accflags='$ASAN_FLAGS_COMMON' -Aldflags='$ASAN_FLAGS_COMMON'"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libapp-nopaste-perl
            - net-tools
            - expect
            - libc6
            - libc6:i386
            - binutils
            - gcc-8
            - g++-8

    # CLEANTEST of minimum supported with non-tracing poisoning, single thread
    - perl: "livebrew_5.8.3_nt_mb"
      env:
        - VCPU_USE=1
        - CLEANTEST=true
        - POISON_ENV=true
        - DBIC_TRACE_PROFILE=console_monochrome
        - BREWVER=5.8.3
        - BREWOPTS="-Dusemorebits"

    # Full Test of minimum supported without threads with plain poisoned trace
    - perl: "livebrew_5.8.3_nt"
      # FIXME - move to bionic
      dist: trusty
      env:
        - CLEANTEST=false
        - POISON_ENV=true
        - DBIC_TRACE=1
        - BREWVER=5.8.3

    # Full Test of minimum supported with threads with non-tracing poisoning
    - perl: "livebrew_5.8.5_thr"
      # FIXME - move to xenial
      dist: trusty
      env:
        - CLEANTEST=false
        - POISON_ENV=true
        - DBIC_TRACE_PROFILE=console
        - BREWVER=5.8.5
        - BREWOPTS="-Duseithreads"

    # CLEANTEST of solaris-like perl with non-tracing poisoning
    - perl: "livebrew_5.8.4_nt"
      dist: precise
      env:
        - CLEANTEST=true
        - POISON_ENV=true
        - DBIC_TRACE_PROFILE=console
        - BREWVER=5.8.4

    # Full test: this particular perl is quite widespread, single thread
    - perl: "livebrew_5.8.8_thr"
      dist: precise
      env:
        - VCPU_USE=1
        - CLEANTEST=false
        - BREWVER=5.8.8
        - BREWOPTS="-Duseithreads"

    # CLEANTEST: this is the perl suse ships, with env poisoning
    - perl: "livebrew_5.10.0_thr_dbg"
      dist: precise
      env:
        - CLEANTEST=true
        - POISON_ENV=true
        - BREWVER=5.10.0
        - BREWOPTS="-DDEBUGGING -Duseithreads"

    # CLEANTEST: this one is in a number of debian-based LTS (test a sane CPAN.pm, single thread)
    - perl: "livebrew_5.14.2_thr_mb"
      # FIXME - move to xenial
      dist: trusty
      env:
        - VCPU_USE=1
        - CLEANTEST=true
        - BREWVER=5.14.2
        - BREWOPTS="-Duseithreads -Dusemorebits"

    ###
    # some permutations of tracing and envvar poisoning

    - perl: "livebrew_5.12.3_thr"
      dist: precise
      env:
        - CLEANTEST=true
        - POISON_ENV=true
        - DBIC_TRACE=1
        - DBIC_MULTICREATE_DEBUG=1
        - DBIC_STORAGE_RETRY_DEBUG=1
        - DBIC_TRACE_PROFILE=console
        - BREWVER=5.12.3
        - BREWOPTS="-Duseithreads"

    - perl: "livebrew_5.16.3_thr_mb"
      # FIXME - move to bionic
      dist: trusty
      env:
        - CLEANTEST=false
        - DBIC_TRACE=1
        - DBICTEST_VERSION_WARNS_INDISCRIMINATELY=1
        - BREWVER=5.16.3
        - BREWOPTS="-Duseithreads -Dusemorebits"

    - perl: "5.18-extras"
      # FIXME - move to xenial
      dist: trusty
      env:
        - CLEANTEST=false
        - POISON_ENV=true
        - DBIC_TRACE=1
        - DBIC_TRACE_PROFILE=console_monochrome
        - DBICTEST_VIA_REPLICATED=0
        - DBICTEST_VERSION_WARNS_INDISCRIMINATELY=1


    ###
    # Start of the allow_failures block

    # ASan-instrumented threaded bleadperl with blead CPAN, full depchain test ( but only DBD::SQLite is used )
    - perl: "livebrew_devcpan_bleadperl_thr_mb_dbg_asan"
      dist: bionic
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - BREWVER=blead
        - CC=gcc-8
        - CXX=g++-8
        # FIXME - something in perl confuses ASan, do no trace leaks for now
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250024.html
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250022.html
        #- PERL_DESTRUCT_LEVEL=2
        - ASAN_OPTIONS=detect_leaks=0
        - ASAN_FLAGS_COMMON="-fsanitize=address -fuse-ld=gold -fno-omit-frame-pointer -g -O2"
        - BREWOPTS="-Duseithreads -Dusemorebits -DDEBUGGING -Dcc=$CC -Accflags='$ASAN_FLAGS_COMMON' -Aldflags='$ASAN_FLAGS_COMMON'"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libapp-nopaste-perl
            - net-tools
            - expect
            - libc6
            - libc6:i386
            - binutils
            - gcc-8
            - g++-8

    # ASan-instrumented threaded bleadperl with blead CPAN and SQLA swapout
    - perl: "livebrew_devcpan_bleadperl_thr_dbg_asan"
      dist: trusty
      env:
        - DBICTEST_SWAPOUT_SQLAC_WITH=SQL::Abstract
        - CLEANTEST=false
        - DEVREL_DEPS=true
        - BREWVER=blead
        - CC=gcc-8
        - CXX=g++-8
        # FIXME - something in perl confuses ASan, do no trace leaks for now
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250024.html
        #         https://www.nntp.perl.org/group/perl.perl5.porters/2018/03/msg250022.html
        #- PERL_DESTRUCT_LEVEL=2
        - ASAN_OPTIONS=detect_leaks=0
        - ASAN_FLAGS_COMMON="-fsanitize=address -fuse-ld=gold -fno-omit-frame-pointer -g -O2"
        - BREWOPTS="-Duseithreads -DDEBUGGING -Dcc=$CC -Accflags='$ASAN_FLAGS_COMMON' -Aldflags='$ASAN_FLAGS_COMMON'"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libapp-nopaste-perl
            - net-tools
            - expect
            - libc6
            - libc6:i386
            - binutils
            - gcc-8
            - g++-8

    # bleadperl with stock CPAN, full depchain test with non-tracing poisoning, single thread
    - perl: "livebrew_bleadperl"
      env:
        - VCPU_USE=1
        - CLEANTEST=true
        - POISON_ENV=true
        - BREWVER=blead

    # Poisoned saneperl with blead CPAN and SQLA swapout, single thread
    - perl: "5.24.3"
      env:
        - DBICTEST_SWAPOUT_SQLAC_WITH=SQL::Abstract
        - VCPU_USE=1
        - CLEANTEST=false
        - DEVREL_DEPS=true
        - POISON_ENV=true
        - MVDT=false

    # threaded oldest possible with blead CPAN
    - perl: "livebrew_devcpan_5.8.1_thr_mb"
      # FIXME - move to bionic
      dist: trusty
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - BREWVER=5.8.1
        - BREWOPTS="-Duseithreads -Dusemorebits"

    # oldest possible with blead CPAN with poisoning and plain trace
    - perl: "livebrew_devcpan_5.8.1"
      dist: precise
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - POISON_ENV=true
        - DBIC_TRACE=1
        - DBICTEST_VERSION_WARNS_INDISCRIMINATELY=1
        - BREWVER=5.8.1

    # 5.8.3 with blead CPAN
    - perl: "livebrew_devcpan_5.8.3_mb"
      dist: trusty
      env:
        - CLEANTEST=false
        - DEVREL_DEPS=true
        - BREWVER=5.8.3
        - BREWOPTS="-Dusemorebits"

    # 5.8.7 threaded with blead CPAN with non-tracing poisoning
    - perl: "livebrew_devcpan_5.8.7_thr"
      dist: precise
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - POISON_ENV=true
        - BREWVER=5.8.7
        - BREWOPTS="-Duseithreads"

    # 5.8.8 threaded MB (exercises P5#72210)
    - perl: "livebrew_devcpan_5.8.8_thr_mb"
      dist: precise
      env:
        - CLEANTEST=true
        - DBICTEST_VERSION_WARNS_INDISCRIMINATELY=1
        - DEVREL_DEPS=true
        - BREWVER=5.8.8
        - BREWOPTS="-Duseithreads -Dusemorebits"

    # 5.10.0 threaded with blead CPAN
    - perl: "livebrew_devcpan_5.10.0_thr_mb"
      dist: precise
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - BREWVER=5.10.0
        - BREWOPTS="-Duseithreads -Dusemorebits"

    # 5.12.1 with blead CPAN
    - perl: "livebrew_devcpan_5.12.1_thr"
      dist: precise
      env:
        - CLEANTEST=true
        - DEVREL_DEPS=true
        - BREWVER=5.12.1
        - BREWOPTS="-Duseithreads"


  # which ones of the above can fail
  allow_failures:

    # these run with various dev snapshots - allowed to fail

    - perl: livebrew_devcpan_bleadperl_thr_dbg_asan
    - perl: livebrew_devcpan_bleadperl_thr_mb_dbg_asan
    - perl: livebrew_bleadperl
    - perl: 5.24.3
    - perl: livebrew_devcpan_5.8.1_thr_mb
    - perl: livebrew_devcpan_5.8.1
    - perl: livebrew_devcpan_5.8.3_mb
    - perl: livebrew_devcpan_5.8.7_thr
    - perl: livebrew_devcpan_5.8.8_thr_mb
    - perl: livebrew_devcpan_5.10.0_thr_mb
    - perl: livebrew_devcpan_5.12.1_thr


###
### For the following two phases -e is *set*
###

before_install:
  # common functions for all run phases below
  #
  # this is an exporter - sourcing it is crucial
  # among other things it also sets -e
  #
  - source maint/travis-ci_scripts/common.bash

  # Sets global envvars, downloads/configures debs based on CLEANTEST
  # Sets extra DBICTEST_* envvars
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/10_before_install.bash

install:
  # Build and switch to a custom perl if requested
  # Configure the perl env, preinstall some generic toolchain parts
  # Possibly poison the environment
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/20_install.bash

###
### From this point on -e is *unset*, rely on travis' error handling
###
  - set +e

before_script:
  # Preinstall/install deps based on envvars/CLEANTEST
  #
  # need to invoke the after_failure script manually
  # because 'after_failure' runs only after 'script' fails
  #
  - maint/getstatus maint/travis-ci_scripts/30_before_script.bash

script:
  # Run actual tests
  #
  - maint/getstatus maint/travis-ci_scripts/40_script.bash


after_success:
  # Check if we can assemble a dist properly if not in CLEANTEST
  #
  ### Need to toggle -e again: work around https://github.com/travis-ci/travis-ci/issues/3533
  - set -e
  - maint/getstatus /bin/bash maint/travis-ci_scripts/50_after_success.bash || ( /bin/bash maint/travis-ci_scripts/50_after_failure.bash && /bin/false )
  - set +e

after_failure:
  # Final sysinfo printout on fail
  #
  - maint/getstatus maint/travis-ci_scripts/50_after_failure.bash

after_script:
  # No tasks yet
  #
  #- maint/getstatus maint/travis-ci_scripts/60_after_script.bash
